version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - app_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  service1:
    build: ./service_1
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 10s
      timeout: 3s
      retries: 3

  service2:
    build: ./service_2
    ports:
      - "8002:8002"     # ✅ Exposes service2 on localhost:8002
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  app_net:
    driver: bridge
